### ISSUE TITLE
关于有些地方TODO区域代码完善的问题

### ISSUE THREAD

**Issue by dangyuluo** [dodgepudding/wechat-php-sdk#172]
代码小子一枚，最近在试用微信公众平台库的时候发现有一些地方存在TODO，比如在checkAuth方法获取access_token的时候没有写cache，当然这些肯定要用户去自己配置，作者不写也是应当并且可以理解的。
对此问题，我的初步想法是，创建一个新类来集成wechat类并覆盖checkAuth方法，这样作者更新后，我只要更新相应的wechat.class.php就可以了，而不用一行一行去改。
但经验不足，继承后，我发现很多Wechat类里面的变量都是定义为private的，这样我继承后就访问不到一些关键变量如appid, appsecret, token等，导致自己重写的checkAuth方法失败。对于这种问题，作者和朋友们有什么好的建议么？

**Comment by dodgepudding** [comment]
嗯，这个问题的确比较严重，我也忍受不了了，已经更新直接加入了三个操作缓存的重载方法，setCache, getCache, removeCache。Thinkphp多写一次代码的确有点多余。

**Comment by dangyuluo** [comment]
另外，代码在SAE上也可以正常运行。
