### ISSUE TITLE
企业号返回 80001错误号是什么原因？

### ISSUE THREAD

**Issue by iMactool** [dodgepudding/wechat-php-sdk#185]
企业号返回 80001错误号是什么原因？errmsg 是空的

**Comment by binsee** [comment]
@wakerman 不知道，没有看到过这个错误号。你是在什么场景下得到这个错误号的？

**Comment by wakerman** [comment]
@binsee  谢谢。我是用ip地址访问的获取token~ 不知道有没有关系。

**Comment by binsee** [comment]
@wakerman IP地址？什么意思

**Comment by binsee** [comment]
@wakerman 知道了
'80001'=>'可信域名没有IPC备案，后续将不能在该域名下正常使用jssdk',

官方刚公布的

**Comment by wakerman** [comment]
@binsee  非常感谢，那天我就换了域名就没事了。
