### ISSUE TITLE
一直显示no access

### ISSUE THREAD

**Issue by doabit** [dodgepudding/wechat-php-sdk#189]
```php
$weObj->valid(); 
```
这一行不注释掉一直显示 no acess，注释掉就好了，不过用了消息加解密方式 这行又不能注释掉，请问怎么解决？

**Comment by binsee** [comment]
被动接口不是让你自己在浏览器里打开的。是让微信服务器访问的。你在浏览器里打开被动接口页面，得到`no acess` 是非常正常的

**Comment by doabit** [comment]
哦，明白了，谢谢
