### ISSUE TITLE
Prpcrypt类构造函数问题

### ISSUE THREAD

**Issue by yhostc** [dodgepudding/wechat-php-sdk#194]
PHP从5.3.3版本开始，在命名空间中，已不再使用与类名同名的方法作为构造函数了。Prpcrypt类中需要升级一下

**Comment by binsee** [comment]
感谢提出这个问题，之前直接移植的官方代码，没考虑到这个问题。近期会修复一下。

**Comment by yhostc** [comment]
赞！
