### ISSUE TITLE
一个很奇怪的问题

### ISSUE THREAD

**Issue by motecshine** [dodgepudding/wechat-php-sdk#196]
数组1

![default](https://cloud.githubusercontent.com/assets/7615270/6035028/7d283cde-ac66-11e4-818e-d70128ffc730.png)

数组2

![2](https://cloud.githubusercontent.com/assets/7615270/6035042/b4fa80fe-ac66-11e4-8d7b-10a791201e6d.png)

第一个数组可以形成 图文消息组，而后一个只能形成一条图文，但是数组结构是一样的

**Comment by yhostc** [comment]
你单独```var_dump($MsgData) ```和```echo count(MsgData)```，观察一下便知

**Comment by motecshine** [comment]
count 是 3 没问题的我又试了一边

**Comment by lichunqiang** [comment]
检查构造好的xml
