### ISSUE TITLE
微信支付封装

### ISSUE THREAD

**Issue by yhostc** [dodgepudding/wechat-php-sdk#197]
Hi, wechat-php-sdk使用起来非常好，但是里面没看到关于支付的。是否有计划将支付部分也封装进来？

**Comment by binsee** [comment]
有V2的，V3的没有封装。我这刚申请升级为V3，之后有空了做下。
PS:今天（2月4日）微信公众平台开放了V2升级V3的接口。在后台微信支付一项中

**Comment by vanjor** [comment]
同求

**Comment by vanjor** [comment]
微信的文档写的狗屎一般，而且各自还不一致，求封装，让大家免交这个学费啊~

**Comment by dodgepudding** [comment]
嗯，去年10月后申请的都是V3的了，有比较完整和统一的功能，譬如退款也另外做了，微信逐渐把账目管理后台功能从财付通剥离出来的，但还没完善。

**Comment by vanjor** [comment]
怪不得，我的应该是V3的，在页面某些地方还能看到 财付通的链接，和微信商务平台搞晕了。
正好项目开发到这里，还恳求大拿封装下V3的支付接口阿，我就先干别的去了_-

**Comment by dodgepudding** [comment]
现在微信有4个后台涉及公众号及商户账号管理，1是公众号管理平台http://mp.weixin.qq.com，2是app管理后台和PC网页授权的管理后台https://open.weixin.qq.com，3是商户管理后台https://pay.weixin.qq.com，4是财付通商户后台http://mch.tenpay.com

**Comment by yhostc** [comment]
包括微信、支付宝的支付部分，其实我们都已经是实现了，只是感觉重复早轮子不是太好。改天时间空闲了，封装出来给大家好了

**Comment by binsee** [comment]
嗯。开源一个好处就是避免重复造轮子
