### ISSUE TITLE
生成永久二维码，不支持 scene_str参数

### ISSUE THREAD

**Issue by pkkgu** [dodgepudding/wechat-php-sdk#210]
1.getQRCode方法没有处理永久二维码的scene_str参数
2.想问下，永久二维码的scene_str和scene_id两个参数可以同时使用吗？

**Comment by pkkgu** [comment]
先不要更新了，已经确认scene_str方式有问题，全部返回45029

{"action_name":"QR_LIMIT_STR_SCENE","action_info":{"scene":{"scene_str":1}}}

{"errcode":45029,"errmsg":"qrcode count out of limit"}

**Comment by binsee** [comment]
是的，很多开发和官方反馈，但没有结果。暂时先放一边等官方修复吧

**Comment by pkkgu** [comment]
建字符串形式的二维码接口已经回复了，SDK可以更新了

**Comment by qinyang1980** [comment]
你好，我开发的时候，也碰到微信的这个问题，全部返回45029，你们后面是咋解决的啊？
谢谢！

**Comment by yuandong618** [comment]
你好，我开发的时候，也碰到微信的这个问题，全部返回45029，你们后面是咋解决的啊？
谢谢！

**Comment by yuandong618** [comment]
我们后来全改为了临时二维码的形式，弃用了永久二维码
