### ISSUE TITLE
你好 关于缓存 ACCESSTOKEN的问题

### ISSUE THREAD

**Issue by motecshine** [dodgepudding/wechat-php-sdk#217]
我用的不是 TP框架，是不是 重载 咱们 SDK里的缓存方法 每次调用的时候优先使用 缓存的ACCESS_TOKEN.

**Comment by binsee** [comment]
@motecshine 如果你使用的是其他框架，可以参考下thinkphp目录下的TPWechat类文件，写一个适配你所用框架的类文件。这样效率高一点。

**Comment by motecshine** [comment]
嗯谢谢
