### ISSUE TITLE
特殊回复问题

### ISSUE THREAD

**Issue by mr-liusg** [dodgepudding/wechat-php-sdk#221]
[wiki](http://mp.weixin.qq.com/wiki/14/89b871b5466b19b3efa4ada8e577d45e.html "wiki")中提到：
1、直接回复空串（指字节长度为0的空字符串，而不是XML结构体中content字段的内容为空）
2、直接回复success

请问使用此框架如何实现？

**Comment by dodgepudding** [comment]
直接exit 或die()
