### ISSUE TITLE
getRevContent()拿到的中文是乱码

### ISSUE THREAD

**Issue by martinzhu** [dodgepudding/wechat-php-sdk#227]
用getRevContent()拿到中文是类似于\xe4\xb8\xad这样的乱码。我拿到这样的乱码无法再想其他的web service发出请求，因为其他的web service无法识别这样的乱码。

这种情况下要怎样转码？或是怎么做？谢谢！

**Comment by martinzhu** [comment]
弄错了。是把内容输出到apache的log下，log无法显示中文。改变输出到指定文件后，输出正常。不好意思。sorry！

**Comment by iliaokun** [comment]
@martinzhu 请问这个怎么改？ 请指教。

**Comment by martinzhu** [comment]
你好，我原来是在linux下输出到log文件中，系统不识别中文。我不清楚的环境是否也不支持中文？

**Comment by martinzhu** [comment]
@iliaokun 
你好，我原来是在linux下输出到log文件中，系统不识别中文。我不清楚的环境是否也不支持中文？
