### ISSUE TITLE
模版消息换行问题

### ISSUE THREAD

**Issue by phpyii** [dodgepudding/wechat-php-sdk#238]
wechat.class.php中自带的方法json_encode 不能正确格式化\n所以导致模版消息无法换行
建议作者能不能考虑把json_encode 这个方法也放到重写里
yii框架自带的就能正确格式化  CJSON::encode($arr);

**Comment by pkkgu** [comment]
这问题向作者提过，但是被忽略了
sendCustomMessage也发现这问题了。
我的解决方法是把
self::json_encode($data))
替换成
urldecode(json_encode($data))

**Comment by cnzhangxl** [comment]
作者的这个确实有问题，但是我直接用json_encode也没问题啊，没有发现作者所说的 “ 微信api不支持中文转义的json结构”的问题，用系统的json_encode能够正常发送显示模板消息

**Comment by dodgepudding** [comment]
这是历史问题，微信后台把json支持修复了，改回去用原生方法好了

**Comment by ww380459000** [comment]
发送模版消息data数据未被替换是什么原因？{"touser":"oiQs4sxNOzvy3PV6BP6H0QzYqXpY","template_id":"WobHv3cNAkrKUL3xFKe7VpZ4gGoqNnCwxWPcObGB2gs","url":"http://weixin.qq.com/download","data":{"first":{"value":"新订单","color":"#173177"},"orderid":{"value":"1001","color":"#173177"},"amount":{"value":"100元","color":"#173177"},"remark":{"value":"测试订单通知","color":"#173177"}}

**Comment by nigelvon** [comment]
最新版的还是发不了模板消息，只能用系统的`json_encode`替代`Wechat::json_encode`

**Comment by KalepSong** [comment]
php5.4 json_encode才支持第二个参数：JSON_UNESCAPED_UNICODE   
中文不会被默认转成unicode

**Comment by ioperat** [comment]
模板换行问题解决了吗？我用/n还是不行啊

**Comment by inroading** [comment]
$data数据在json_encode的基础上再包裹一个urldecode就可以了，urldecode(json_encode($data))

最初的梦想 <notifications@github.com> 于2020年12月31日周四 下午2:53写道：
