### ISSUE TITLE
getForeverMedia获取图片返回空串，是怎么回事？

### ISSUE THREAD

**Issue by ww380459000** [dodgepudding/wechat-php-sdk#267]
curl "https://api.weixin.qq.com/cgi-bin/material/get_material?access_token=xxxx" -d '{"media_id":"xxxx"}' >bb.jpg
但这种可以获取到，有人遇到过吗？

**Comment by lifeha** [comment]
file_put_contents('1.jpg',$weixin->getForeverMedia('Mediaid'));

**Comment by ww380459000** [comment]
$wechat->getForeverMedia('N2fzkwBWXXXXXXXXXXXXWcN07ex-6EueKBRpykziGyYI')这个都获取不到数据，你可以吗？

**Comment by ww380459000** [comment]
是php7的原因，sorry，可以考虑下7的兼容哈

**Comment by ww380459000** [comment]
不是版本的问题
