### ISSUE TITLE
Tinkphp框架用wechat-php-sdk 接入微信时，Windows服务器一直是url超时，求指教

### ISSUE THREAD

**Issue by fancdevin** [dodgepudding/wechat-php-sdk#328]
Windows服务器下面一直报URL超时不能接入（liunx环境下没有问题）
修改链接数据库方式127.0.0.1或者localhost还是不行。
请问有解决方法么 ？

**Comment by lzj500** [comment]
你用微信接口调试工具，看一下服务器返回吧，可能多了一个空白行\n，导致输出不是标准的XML
